import type { CapabilityDefinition, CapabilityId } from '@iris/domain';

const DEFINITIONS: readonly CapabilityDefinition[] = [
  { id: 'runtime.status', title: 'Read runtime status', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: false, implemented: true },
  { id: 'project.list', title: 'List registered projects', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: false, implemented: true },
  { id: 'project.info', title: 'Read registered project metadata', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'project.git_status', title: 'Read project Git status', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'project.search', title: 'Search registered project text', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'project.test.run', title: 'Run declared project test script', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'mission.list', title: 'List mission execution records', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: false, implemented: true },
  { id: 'mission.get', title: 'Read mission execution record', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: false, implemented: true },
  { id: 'mission.create', title: 'Register mission identity', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'mission.state.set', title: 'Record mission state', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'mission.task.create', title: 'Register mission task', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'mission.task.state.set', title: 'Record mission task state', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'mission.action.prepare', title: 'Prepare governed mission action', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'mission.supervisor_gate.set', title: 'Record supervisor gate state', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'session.create', title: 'Create local session', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'session.delete', title: 'Delete owned local session', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'session.current_project.set', title: 'Set session current project', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'session.instruction.submit', title: 'Submit session instruction', riskClass: 'LOW', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'project.register', title: 'Register project root', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'project.default.set', title: 'Set machine default project', riskClass: 'MODERATE', requiredScope: 'MACHINE', mutation: true, implemented: true },
  { id: 'file.read', title: 'Read project file', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'file.write', title: 'Create or edit project file', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'file.edit', title: 'Apply one exact project file edit', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'file.delete', title: 'Delete project file', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'directory.create', title: 'Create project directory', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'directory.delete', title: 'Remove empty project directory', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'workspace.list', title: 'List project workspaces', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'workspace.get', title: 'Read project workspace metadata', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'workspace.create_scratch', title: 'Create governed project scratch workspace', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'workspace.revoke_scratch', title: 'Revoke governed project scratch workspace', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'fs.list', title: 'List bounded workspace filesystem inventory', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'fs.stat', title: 'Read workspace filesystem metadata', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'fs.read', title: 'Read bounded workspace file content', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'fs.write', title: 'Create, replace, or append workspace file', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'fs.edit', title: 'Apply exact workspace file edit', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'fs.mkdir', title: 'Create workspace directory', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'fs.delete', title: 'Delete bounded workspace entry', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'fs.hash', title: 'Stream workspace file SHA-256', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'fs.find', title: 'Find bounded workspace entries/text', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'artifact.stat', title: 'Read governed artifact metadata', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'artifact.open_ref', title: 'Open governed artifact reference', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'artifact.register_existing', title: 'Register verified existing workspace file as artifact', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'artifact.release', title: 'Release governed artifact registration', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'shell.run', title: 'Run governed local process synchronously', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'shell.start', title: 'Start governed durable local process', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'job.status', title: 'Read governed durable job status', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'job.logs', title: 'Read bounded governed durable job logs', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'job.result', title: 'Read governed durable job result', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'job.cancel', title: 'Cancel verified governed durable job process group', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'project.command.run', title: 'Run declared project validation script', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'project.validation.discover', title: 'Discover declared project validation scripts', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'project.validation.start', title: 'Start a declared project validation job', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'project.validation.job.read', title: 'Read a governed project validation job', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.status', title: 'Read governed Git status', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.head', title: 'Read governed Git HEAD', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.diff', title: 'Read governed Git diff', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.log', title: 'Read bounded governed Git log', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.show', title: 'Read bounded governed Git object presentation', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.cat_file', title: 'Inspect bounded governed Git object metadata/content', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.merge_base', title: 'Read governed Git merge base', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.ancestry', title: 'Read governed Git ancestry result', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.refs', title: 'Read bounded governed Git refs', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.branch_list', title: 'Read governed Git branch list', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.worktree_list', title: 'Read governed Git worktree list without authorizing paths', riskClass: 'LOW', requiredScope: 'PROJECT', mutation: false, implemented: true },
  { id: 'git.branch_create', title: 'Create governed Git branch without checkout', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.worktree_add', title: 'Create and authorize verified Git WORKTREE workspace', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.worktree_remove', title: 'Remove verified clean governed Git WORKTREE workspace', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.add', title: 'Stage explicit bounded governed Git paths', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.commit', title: 'Commit explicit bounded governed Git paths', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.fetch', title: 'Fetch configured governed Git remote', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'git.push', title: 'Push governed safe feature branch to configured remote', riskClass: 'HIGH', requiredScope: 'OWNER', mutation: true, implemented: true },
  { id: 'git.local', title: 'Bounded local project Git operation', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: true },
  { id: 'runtime.lifecycle', title: 'Local runtime lifecycle', riskClass: 'MODERATE', requiredScope: 'RUNTIME_DATA', mutation: true, implemented: true },
  { id: 'web.lifecycle', title: 'Local Web development lifecycle', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: false },
  { id: 'package.project', title: 'Project package-manager operation', riskClass: 'MODERATE', requiredScope: 'PROJECT', mutation: true, implemented: false },
  { id: 'policy.mode.set', title: 'Change machine permission mode', riskClass: 'HIGH', requiredScope: 'OWNER', mutation: true, implemented: true },
  { id: 'credential.mutate', title: 'Create or change credentials', riskClass: 'HIGH', requiredScope: 'OWNER', mutation: true, implemented: false },
  { id: 'remote.publish', title: 'Push current feature branch to configured origin', riskClass: 'HIGH', requiredScope: 'OWNER', mutation: true, implemented: true },
  { id: 'system.sudo', title: 'System privilege escalation', riskClass: 'SYSTEM', requiredScope: 'OWNER', mutation: true, implemented: false },
] as const;

const BY_ID = new Map<CapabilityId, CapabilityDefinition>(DEFINITIONS.map((definition) => [definition.id, definition]));

export function listCapabilities(): readonly CapabilityDefinition[] {
  return DEFINITIONS;
}

export function capabilityDefinition(id: string): CapabilityDefinition | null {
  return BY_ID.get(id as CapabilityId) ?? null;
}
