export const PHASE8_V230_CATALOG_FIXTURE = {
  catalogVersion: '2.3.0',
  schemaVersion: '2026-07-28',
  legacyToolNames: [
    'runtime_status',
    'list_projects',
    'project_info',
    'git_status',
    'search',
    'mission_list',
    'session_open',
    'session_get',
    'session_close',
    'workspace_select',
    'mission_list_waiting_supervisor',
    'mission_get',
    'mission_events',
    'mission_directive',
    'mission_orchestrator_handoff',
    'mission_create',
    'mission_state_set',
    'mission_task_create',
    'mission_task_state_set',
    'mission_action_prepare',
    'mission_supervisor_gate_set',
    'project_test_run',
    'project_validation_run',
    'project_validation_discover',
    'project_validation_start',
    'project_validation_job',
    'git_local',
    'remote_publish',
    'file_read',
    'file_write',
    'file_edit',
    'file_delete',
    'directory_create',
    'directory_delete',
    'mission_start',
    'mission_checkpoint',
    'mission_resume',
    'mission_rebind',
    'mission_cancel',
    'mission_complete',
    'mission_evidence',
    'catalog_identity',
  ],
  legacyCompatibilityHash: '1770afee25ea16845137464de238c36c51465ada722ad7206cee38f14b5e0f54',
  proToolNames: ['list_projects', 'project_info', 'git_status', 'file_read', 'search'],
  proCompatibilityHash: 'ae0be3214fdf8b60275027394a7bd43d5b5121a69f31bebc3011b01789ce15e1',
} as const;

export const PHASE8_COMPATIBILITY_WRAPPERS = [
  'git_status',
  'search',
  'project_test_run',
  'project_validation_run',
  'project_validation_discover',
  'project_validation_start',
  'project_validation_job',
  'git_local',
  'remote_publish',
  'file_read',
  'file_write',
  'file_edit',
  'file_delete',
  'directory_create',
  'directory_delete',
] as const;
