import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { FakeMobileAdapter, effects, redactLog } from './fake.ts';
const emulator = { serial: 'emulator-5554', state: 'device', transport: 'emulator', model: 'synthetic', manufacturer: 'fake', androidVersion: '14', apiLevel: 34, kind: 'emulator', connectionId: 'epoch-1' };
const phone = { ...emulator, serial: 'fake-phone', kind: 'physical', transport: 'usb' };
const shot = { adapter: 'adb', operation: { kind: 'screenshot' } };
const target = { deviceSerial: emulator.serial };
function fixture(devices = [emulator]) { const f = new FakeMobileAdapter(devices); f.granted = true; return f; }
const ctx = () => ({ operationId: 'op-1', timeoutMs: 100, signal: new globalThis.AbortController().signal });
const run = (f, t = target, op = shot, c = ctx()) => f.execute(t, op, c);
test('01 zero devices fails', async () => { await assert.rejects(run(fixture([])), /DEVICE_MISSING/); });
test('02 one emulator never implicit', async () => { await assert.rejects(run(fixture(), {}), /EXPLICIT_DEVICE/); });
test('03 emulator plus physical never implicit', async () => { await assert.rejects(run(fixture([emulator, phone]), {}), /EXPLICIT_DEVICE/); });
test('04 explicit valid serial evidence', async () => { assert.equal((await run(fixture())).evidence.serial, emulator.serial); });
test('05 explicit missing serial', async () => { await assert.rejects(run(fixture(), { deviceSerial: 'absent' }), /DEVICE_MISSING/); });
test('06 offline', async () => { await assert.rejects(run(fixture([{ ...emulator, state: 'offline' }])), /DEVICE_UNAVAILABLE/); });
test('07 disappears during operation', async () => { const f = fixture(); f.duringOperation = () => { f.inventory = []; }; await assert.rejects(run(f), /DEVICE_MISSING/); });
test('08 wrong device fallback prohibited', async () => { const f = fixture([emulator, phone]); f.duringOperation = () => { f.inventory = [phone]; }; await assert.rejects(run(f), /DEVICE_MISSING/); assert.deepEqual(f.calls, [emulator.serial]); });
test('09 stale Appium session', async () => { await assert.rejects(run(fixture(), target, { adapter: 'appium', operation: { kind: 'source', sessionId: 'old' } }), /STALE_SESSION/); });
test('10 screenshot sensitivity', async () => { const { artifact } = await run(fixture()); assert.equal(artifact.sensitivity, 'restricted'); assert.equal(artifact.retention, 'memory-only'); assert.equal(artifact.redaction, 'required-before-export'); });
test('11 log secret redaction', () => { const output = redactLog('Authorization: Bearer abc\nPASSWORD=def account-123', ['account-123']); for (const secret of ['abc', 'def', 'account-123']) assert.ok(!output.includes(secret)); });
test('12 APK hash recorded', async () => { const apk = new globalThis.TextEncoder().encode('synthetic APK bytes'); const hash = createHash('sha256').update(apk).digest('hex'); assert.equal((await run(fixture(), target, { adapter: 'adb', operation: { kind: 'install', apk, expectedSha256: hash } })).evidence.apkSha256, hash); });
test('13 timeout', async () => { const f = fixture(); f.elapsedMs = 100; await assert.rejects(run(f), /TIMEOUT/); });
test('14 cancellation mid-operation', async () => { const f = fixture(); const controller = new globalThis.AbortController(); f.duringOperation = () => controller.abort(); await assert.rejects(run(f, target, shot, { ...ctx(), signal: controller.signal }), /CANCELLED/); });
test('15 Robot job correlation', async () => { assert.equal((await run(fixture(), target, shot, { ...ctx(), jobId: 'robot-job-42' })).evidence.jobId, 'robot-job-42'); });
test('16 immutable binding and reconnect rejection', async () => { const f = fixture(); f.bind('binding-1', emulator.serial); assert.throws(() => f.bind('binding-1', phone.serial), /IMMUTABLE/); await run(f, { deviceBindingId: 'binding-1' }); f.inventory = [{ ...emulator, connectionId: 'epoch-2' }]; await assert.rejects(run(f, { deviceBindingId: 'binding-1' }), /STALE_BINDING/); });
test('17 discovery does not authorize', async () => { const f = new FakeMobileAdapter([emulator]); assert.equal((await f.devices()).length, 1); assert.equal(f.bindingCount, 0); await assert.rejects(run(f), /AUTHORIZATION/); assert.equal(f.calls.length, 0); });
test('18 shell root and arbitrary commands denied', () => { for (const command of ['su', 'root', 'rm -rf /']) assert.throws(() => effects({ adapter: 'adb', operation: { kind: 'shell', profile: 'android-properties-v1', command } }), /SHELL_POLICY/); assert.deepEqual(effects({ adapter: 'adb', operation: { kind: 'shell', profile: 'android-properties-v1', command: 'get_android_version' } }), ['READ', 'EXECUTE']); });
test('19 APK mismatch has no dispatch', async () => { const f = fixture(); await assert.rejects(run(f, target, { adapter: 'adb', operation: { kind: 'install', apk: new Uint8Array(), expectedSha256: 'bad' } }), /APK_HASH/); assert.equal(f.calls.length, 0); });
test('20 Appium sessions pinned to device', async () => { const f = fixture([emulator, phone]); await run(f, target, { adapter: 'appium', operation: { kind: 'session', action: 'create' } }); await assert.rejects(run(f, { deviceSerial: phone.serial }, { adapter: 'appium', operation: { kind: 'contexts', sessionId: 'op-1' } }), /STALE_SESSION/); const result = await run(f, target, { adapter: 'appium', operation: { kind: 'source', sessionId: 'op-1' } }); assert.equal(result.artifact.sensitivity, 'restricted'); });
test('21 invalid limits and serial rejected', async () => { await assert.rejects(run(fixture(), { deviceSerial: '-s bad' }), /EXPLICIT_DEVICE/); await assert.rejects(run(fixture(), target, { adapter: 'adb', operation: { kind: 'logcat', maxBytes: Infinity } }), /INVALID_LIMIT/); });
test('22 pre-cancelled has no dispatch', async () => { const f = fixture(); const controller = new globalThis.AbortController(); controller.abort(); await assert.rejects(run(f, target, shot, { ...ctx(), signal: controller.signal }), /CANCELLED/); assert.equal(f.calls.length, 0); });
